#title: Prapti Kansagra
#logo: 
#description:
#show_downloads: true
#theme: jekyll-theme-minimal


title: Prapti Kansagra
description: Business Intelligence Analyst | Data Science | Analytics Portfolio
theme: jekyll-theme-minimal

logo: /Headshot.jpg
show_downloads: true

markdown: kramdown

plugins:
  - jekyll-seo-tag

email: pkansagra06@gmail.com
linkedin: https://www.linkedin.com/in/praptikansagra


