#title: Prapti Kansagra
#logo: 
#description:
#show_downloads: true
#theme: jekyll-theme-minimal


title: Prapti Kansagra
description: Data Scientist & AI/ML Enthusiast
logo: Headshot.jpg
show_downloads: true
theme: jekyll-theme-midnight


# At the bottom of _config.yml
sass:
  style: compressed

