#title: Prapti Kansagra
#logo: 
#description:
#show_downloads: true
#theme: jekyll-theme-minimal


title: Prapti Kansagra
description: BI/DA Analyst | Data Science | AI/ML 
theme: jekyll-theme-minimal

logo: /Headshot.jpg
show_downloads: false
markdown: kramdown


